theme = "catppuccin-mocha"
[editor]
bufferline = "multiple"
color-modes = true
default-line-ending = "lf"
line-number = "relative"
popup-border = "all"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"

[editor.indent-guides]
character = "┆"
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.insert]
C-s = ["normal_mode", ":w"]

[keys.normal]
C-r = ":reload"
C-s = ":w"
